### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by datapythonista** [pydatadelhi/pydatadelhi.github.io#4]
Looks like we were forcing the https on delhi.pydata.org from the pydata.org domain configuration site. The best way to do it is to force https in the GitHub pages settings of this repo. I had to remove that configuration in our side (pydata.org), so now https is not being forced. Can you check the checkbox to force https in your side (GitHub) please? Thank you!

**Comment by sanketverma1704** [comment]
Hi @datapythonista.
Thanks for letting us know. I've enabled force HTTPS from GitHub.
