### ISSUE TITLE
Add contributors to `README.md`

### ISSUE THREAD

**Issue by sanketverma1704** [pydatadelhi/pydatadelhi.github.io#5]
Adding existing contributors list to the `README.md` via [all-contributors](https://github.com/all-contributors/all-contributors). See [emoji-key](https://allcontributors.org/docs/en/emoji-key).

**Comment by MSanKeys963** [comment]
@all-contributors, please add @MSanKeys963 for code, doc and data.

**Comment by sanketverma1704** [comment]
@all-contributors please add @MSanKeys963 for Code, Documentation, Data.
